---
kind: pipeline
name: default

steps:
- name: publish_webapp
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: validateur_webapp/Dockerfile
    context: validateur_webapp
    repo: "montmassoncircleci/validateur_webapp"
    password: 
      from_secret: password
    username: 
      from_secret: username      
  when:
    event:
    - push
    - tag
- name: publish_api
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: validateur_api/Dockerfile
    context: validateur_api
    repo: montmassoncircleci/validateur_api
    password: 
      from_secret: password
    username: 
      from_secret: username      
  when:
    event:
    - push
    - tag
