version: '2'
services:
  rcgechvalidator:
    build:
      context: ./validateur_api
      dockerfile: Dockerfile
    environment:
      - TX_HEX=d3851f8ee9bbd79a4cf332999a89a4b2c6b8d5c4c0c001ea85e95ab7997843c0
      - WS_URI=https://rinkeby.infura.io/v3/3915211d82c546beaf5336b3c9b9b99a
      - LOCKED_ADDR=0x533a245f03a1a46cacb933a3beef752fd8ff45c3,0x3ab05401c0d9483dbeb108b741248bb8e82e323d,0x88ab30749e745a66262275e0489373d3e0781e74
      - TIMEOUT=1653618789,1653618789,1653618789
    working_dir: /app
    command: "/app/api --host 0.0.0.0 --port=8090"
    ports:
      - "0.0.0.0:8090:8090"
      
  webapp:
    build:
      context: ./validateur_webapp
    ports:
      - "0.0.0.0:8001:8080"
    environment:
      - API_HOST=rcgechvalidator:8090 # API host, is equal to the <api container name>:<port>
      - MAIN_URI=ctivalidator
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=foo@example.com
      - CSRF_TIME_LIMIT=360
    working_dir: /app
    command: /app/webapp

  # SSL Let's Encrypt config

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/live/example.com:/etc/nginx/certs:ro # Edit path to right domain name
      - /usr/share/nginx/html
      - /etc/nginx/vhost.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-proxy-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /etc/letsencrypt/live/example.com:/etc/nginx/certs:rw # Edit path to right domain name
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "FILES_PERMS=600"
    volumes_from:
      - nginx-proxy



# Add these env vars to services that need to be reached from the Internet
# VIRTUAL_HOST=example.com ; LETSENCRYPT_HOST=example.com ; LETSENCRYPT_EMAIL= foo@example.com