version: '2'
services:
  rcgechvalidator:
    image: blockchainpartnerhub/geneva_validateur_rcgechvalidator:1.0
    environment:
      - TX_HEX=d3851f8ee9bbd79a4cf332999a89a4b2c6b8d5c4c0c001ea85e95ab7997843c0
      - WS_URI=https://rinkeby.infura.io/v3/afeacc980c634655875d915ed65cb0e4 # WS url to connect to the blockchain
      - LOCKED_ADDR=0x533a245f03a1a46cacb933a3beef752fd8ff45c3,0x3ab05401c0d9483dbeb108b741248bb8e82e323d,0x88ab30749e745a66262275e0489373d3e0781e74 # List of addresses that were used in the past
      - TIMEOUT=1653618789,1653618789,1653618789 # Unix time stamp to setup the moment from when the key is considered invalid
    working_dir: /app
    command: "/app/api --host 0.0.0.0 --port=8090"

  webapp:
    image: blockchainpartnerhub/geneva_validateur_webapp:1.0
    ports:
      - "0.0.0.0:8001:8080"
    environment:
      - API_HOST=rcgechvalidator:8090 # API host, is equal to the <api container name>:<port>
      - MAIN_URI=ctivalidator
      - VIRTUAL_HOST=example.com
    working_dir: /app
    command: /app/webapp
    volumes:
      - "./myservice.cert:/app/myservice.cert"
      - "./myservice.key:/app/myservice.key"


  # SSL Let's Encrypt config

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /path/to/certs/:/etc/nginx/certs:ro # Edit path to the right certs folder, name should be example.com.crt and example.com.key
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html



# Add these env vars to services that need to be reached from the Internet
# VIRTUAL_HOST=example.com ; LETSENCRYPT_HOST=example.com ; LETSENCRYPT_EMAIL= foo@example.com